#!/bin/bash
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=32
#SBATCH --time=999:00:00
#SBATCH -p compute

cd $SLURM_SUBMIT_DIR

mpirun -np 64 $HOME/cardinal/cardinal-opt -i coupled_nek_master.i > logfile
